apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: style-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/de2pakchauhan/style-store-gitops
    targetRevision: HEAD
    path: K8s              # <--- This is now correct
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
